spring:
  application:
    name: ${CLASS_SERVICE_NAME}

server:
  port: ${CLASS_SERVICE_PORT}

discovery:
  name: ${DISCOVERY_SERVICE_NAME}
file:
  name: ${FILE_SERVICE_NAME}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${DISCOVERY_SERVICE_LOCAL_HOST}:${DISCOVERY_SERVICE_PORT}/eureka