spring:
  application:
    name: ${CLASS_SERVICE_NAME}

server:
  port: ${CLASS_SERVICE_PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${DISCOVERY_SERVICE_NAME}:${DISCOVERY_SERVICE_PORT}/eureka