spring:
  application:
    name: ${DISCOVERY_SERVICE_NAME}
server:
  port: ${DISCOVERY_SERVICE_PORT}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true